model_family: llama2-7b
model_path: null

lr: 5e-5
weight_decay: 0.01
split: forget10
data_path: locuslab/TOFU
batch_size: 5 # 20 for phi
gradient_accumulation_steps: 7 # 1 for phi
num_epochs: 10
forget_loss: null # grad_diff # subdpo # 

retain_wt: 1
retain_type: NLL
alpha: 1
beta: null # 0.1
augment_k: 1
start_with_eval: true
save_dir: null
overwrite_dir: true
save_model: false
eval_while_train: true
eval_only: false
seed: null

eval:
  # get retain result paths from the data folder
  # for phi, forget90 
  # retain_result: data/ft_epoch5_lr2e-05_phi_retain90_wd0.01/eval_results/ds_size300/eval_log_aggregated.json
  # llama2-7b
  # retain_result: data/ft_epoch5_lr1e-05_llama2-7b_retain90_wd0.01/eval_results/ds_size300/eval_log_aggregated.json
  # no need to change, main code sets retain file directly
  model_path: ${..model_path}
  model_family: ${..model_family}
  save_dir: ${..save_dir}
  data_path: [locuslab/TOFU, locuslab/TOFU, locuslab/TOFU, locuslab/TOFU]
  split: ${..split}_perturbed
  split_list:
    - retain_perturbed
    - real_authors_perturbed
    - world_facts_perturbed
    - ${split}

  eval_task: [eval_log, eval_real_author_wo_options, eval_real_world_wo_options, eval_log_forget]
  question_key: [question, question, question, question]
  answer_key: [answer, answer, answer, answer]
  base_answer_key: [paraphrased_answer, answer, answer, paraphrased_answer]
  perturbed_answer_key: [perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer]

  generation:
    max_length: 200
    max_new_tokens: null

  save_generated_text: true

  ds_size: 300

  overwrite: true
  use_pretrained: false

  batch_size: 25 # can change this by forget split size
  retain_result: null